src/Entity/Agent.php
<?php

namespace App\Entity;
use App\Repository\AgentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=AgentRepository::class)
 */
class Agent
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotNull(message="Le nom est obligatoire")
     * @Assert\Length(
     *     min=2,
     *     max=50,
     *     minMessage= "2 caractères minimum",
     *     maxMessage ="50 caractères maximum"
     * )
     */
    private $agent_last_name;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotNull(message="Le prénom est obligatoire")
     * @Assert\Length(
     *     min=2,
     *     max=50,
     *     minMessage= "2 caractères minimum",
     *     maxMessage ="50 caractères maximum"
     * )
     */
    private $agent_first_name;

    /**
     * @ORM\Column(type="date")
     */
    private $agent_birth_date;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotNull(message="Le code est obligatoire")
     * @Assert\Length(
     *     min=2,
     *     max=50,
     *     minMessage= "2 caractères minimum",
     *     maxMessage ="50 caractères maximum"
     * )
     */
    private $agent_identification_code;

    /**
     * @ORM\ManyToOne(targetEntity=Nationality::class, inversedBy="agents")
     */
    private $nationality;    
   
    /**
     * @ORM\ManyToMany(targetEntity=Speciality::class, inversedBy="agents")
     * @ORM\JoinColumn(nullable=false)
     */
    private $specialities;

     /**
     * @ORM\ManyToMany(targetEntity=Mission::class, mappedBy="agent")
     */
    private $missions;

    public function __construct()
    {
        $this->specialities = new ArrayCollection();
        $this->missions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAgentLastName(): ?string
    {
        return $this->agent_last_name;
    }

    public function setAgentLastName(string $agent_last_name): self
    {
        $this->agent_last_name = $agent_last_name;

        return $this;
    }

    public function getAgentFirstName(): ?string
    {
        return $this->agent_first_name;
    }

    public function setAgentFirstName(string $agent_first_name): self
    {
        $this->agent_first_name = $agent_first_name;

        return $this;
    }

    public function getAgentBirthDate(): ?\DateTimeInterface
    {
        return $this->agent_birth_date;
    }

    public function setAgentBirthDate(\DateTimeInterface $agent_birth_date): self
    {
        $this->agent_birth_date = $agent_birth_date;

        return $this;
    }

    public function getAgentIdentificationCode(): ?string
    {
        return $this->agent_identification_code;
    }

    public function setAgentIdentificationCode(string $agent_identification_code): self
    {
        $this->agent_identification_code = $agent_identification_code;

        return $this;
    }

    public function getNationality(): ?nationality
    {
        return $this->nationality;
    }

    public function setNationality(?nationality $nationality): self
    {
        $this->nationality = $nationality;

        return $this;
    }

    /**
     * @return Collection|Speciality[]
     */
    public function getSpecialities(): Collection
    {
        return $this->specialities;
    }

    public function addSpeciality(Speciality $speciality): self
    {
        if (!$this->specialities->contains($speciality)) {
            $this->specialities[] = $speciality;
            $speciality->addAgent($this);
        }

        return $this;
    }

    public function removeSpeciality(Speciality $speciality): self
    {
        if ($this->specialities->removeElement($speciality)) {
            $speciality->removeAgent($this);
        }

        return $this;
    }

    /**
     * @return Collection|Mission[]
     */
    public function getMissions(): Collection
    {
        return $this->missions;
    }

    public function addMission(Mission $mission): self
    {
        if (!$this->missions->contains($mission)) {
            $this->missions[] = $mission;
            $mission->addAgent($this);
        }

        return $this;
    }

    public function removeMission(Mission $mission): self
    {
        if ($this->missions->removeElement($mission)) {
            $mission->removeAgent($this);
        }

        return $this;
    }

    public function __toString()
    {
        return $this->agent_last_name ;
    }    
    

   
    
}

src/Entity/Speciality.php
<?php

namespace App\Entity;

use App\Repository\SpecialityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SpecialityRepository::class)
 */
class Speciality
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $speciality_name;

    /**
     * @ORM\OneToMany(targetEntity=Mission::class, mappedBy="speciality")
     */
    private $missions;    

    /**
     * @ORM\ManyToMany(targetEntity=Agent::class, mappedBy="agents")
     */
    private $agent;    

    public function __construct()
    {
        $this->missions = new ArrayCollection();
        $this->agent = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSpecialityName(): ?string
    {
        return $this->speciality_name;
    }

    public function setSpecialityName(string $speciality_name): self
    {
        $this->speciality_name = $speciality_name;

        return $this;
    }

    /**
     * @return Collection|Mission[]
     */
    public function getMissions(): Collection
    {
        return $this->missions;
    }

    public function addMission(Mission $mission): self
    {
        if (!$this->missions->contains($mission)) {
            $this->missions[] = $mission;
            $mission->setSpeciality($this);
        }

        return $this;
    }

    public function removeMission(Mission $mission): self
    {
        if ($this->missions->removeElement($mission)) {
            // set the owning side to null (unless already changed)
            if ($mission->getSpeciality() === $this) {
                $mission->setSpeciality(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|agent[]
     */
    public function getAgent(): Collection
    {
        return $this->agent;
    }

    public function addAgent(agent $agent): self
    {
        if (!$this->agent->contains($agent)) {
            $this->agent[] = $agent;
        }

        return $this;
    }

    public function removeAgent(agent $agent): self
    {
        $this->agent->removeElement($agent);

        return $this;
    }    

    public function __toString()
    {
        return $this->speciality_name ;
    }    

}

src/Form/AgentType.php
<?php

namespace App\Form;
use App\Entity\Agent;
use App\Entity\Nationality;
use App\Entity\Speciality;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class AgentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder           
            
            ->add('agent_last_name' , TextType::class, [
                'label'=>'Nom',
                ])
            
            ->add('agent_first_name' , TextType::class, [
                'label'=>'Prénom',
                ])

            ->add('agent_birth_date' ,  DateType::class,[
                'widget' => 'choice',
                'format' => 'd-M-y',
                'years' => range(date("Y") - 60, date("Y") - 10) ,
                'label'=>'Date de Naissance',
                ])
            
            ->add('agent_identification_code' , TextType::class, [
                'label'=>'Code d\'Identification',
                ])
            
            ->add('nationality', EntityType::class, [
                'class' => Nationality::class,
                'choice_label' => 'nationality_name',
                'label'=>'Nationalité',
                'required' => true,
            ])

            ->add('specialities' , EntityType::class, [
                'choice_label' => 'speciality_name', 
                'class' => Speciality::class,
                'label'=>'Spécialité',                
                'multiple' => true,               
                'required' => true,
            ])        
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Agent::class,
        ]);
    }
}

src/Controller/AgentController.php
<?php

namespace App\Controller;

use App\Entity\Agent;
use App\Form\AgentType;
use App\Repository\AgentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class AgentController extends AbstractController
{
    /**
     * @Route("/admin/agent", name="agent_index", methods={"GET"})
     */
    public function index(AgentRepository $agentRepository): Response
    {
        return $this->render('agent/index.html.twig', [
            'agents' => $agentRepository->findAll(),
        ]);
    }

    /**
     * @Route("/admin/agent/new", name="agent_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $agent = new Agent();
        $form = $this->createForm(AgentType::class, $agent);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($agent);
            $entityManager->flush();

            return $this->redirectToRoute('agent_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('agent/new.html.twig', [
            'agent' => $agent,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/admin/agent/{id}", name="agent_show", methods={"GET"})
     */
    public function show(Agent $agent): Response
    {
        return $this->render('agent/show.html.twig', [
            'agent' => $agent,
        ]);
    }

    /**
     * @Route("/admin/agent/{id}/edit", name="agent_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Agent $agent, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AgentType::class, $agent);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('agent_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('agent/edit.html.twig', [
            'agent' => $agent,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/admin/agent/{id}", name="agent_delete", methods={"POST"})
     */
    public function delete(Request $request, Agent $agent, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$agent->getId(), $request->request->get('_token'))) {
            $entityManager->remove($agent);
            $entityManager->flush();
        }

        return $this->redirectToRoute('agent_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/agent/_delete_form.html.twig
<form method="post" action="{{ path('agent_delete', {'id': agent.id}) }}" onsubmit="return confirm('Etes vous sur de vouloir supprimmer cet item ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ agent.id) }}">
    <button class="btn btn-danger space_4">Supprimer</button>
</form>

templates/agent/_form.html.twig
{{ form_start(form) }}
    
        {{ form_widget(form) }}
        
            <button class="btn btn-success space_4">{{ button_label|default('Enregistrer') }}</button>
        
 
{{ form_end(form) }}

templates/agent/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier un Agent{% endblock %}

{% block main %}

 <div class="row">

    <div class="col-4"></div>           

    <div class="col-4 space_3">  
        
    {{ include('agent/_form.html.twig', {'button_label': 'Modifier'}) }}   

    {{ include('agent/_delete_form.html.twig') }}

    <a href="{{ path('agent_index') }}">Retour à la liste</a>

  </div>
 </div>

{% endblock %}

templates/agent/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des Agents{% endblock %}

 {% block main %}
  

    <table class="table">
        <thead>
            <tr>                
                <th>Nom</th>
                <th>Prénom</th>
                <th>Date de naissance</th>
                <th>Code d'identification</th>
                <th>Nationnalité</th>
                <th>Spécialité</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for agent in agents %}
            <tr>                
                <td>{{ agent.agentLastName }}</td>
                <td>{{ agent.agentFirstName }}</td>
                <td>{{ agent.agentBirthDate ? agent.agentBirthDate|date('Y-m-d') : '' }}</td>
                <td>{{ agent.agentIdentificationCode }}</td>                 
                <td>{{ agent.nationality }}</td>   

                <td>
					{% for agents in agent.specialities %}
						<li>{{agents.specialityName}}</li>
					{% else %}
                     <li><em>vide</em></li>
                    {% endfor %}
				</td>      
                            
                <td>
                    <a href="{{ path('agent_show', {'id': agent.id}) }}">Voir</a>
                    {% if is_granted('ROLE_ADMIN') %}
                        <a href="{{ path('agent_edit', {'id': agent.id}) }}">Modifier</a>               
                    {% endif %}                    
                </td>
                
            </tr>
        {% else %}
            <tr>
                <td colspan="6">Vide</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if is_granted('ROLE_ADMIN') %}
            <a href="{{ path('agent_new') }}">Création nouvel Agent</a>           
    {% endif %}    
    

  {% endblock %}

templates/agent/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Création nouvel Agent{% endblock %}

{% block main %}

  <div class="row space_3">

    <div class="col-4"></div>           

    <div class="col-4">  
   
        {{ include('agent/_form.html.twig') }}

        <a href="{{ path('agent_index') }}">Retour à la liste</a>

  </div>
 </div>

{% endblock %}

templates/agent/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Agent{% endblock %}

{% block main %}

 <div class="row">

    <div class="col-4"></div>           

    <div class="col-4">  
    
        <table class="table">
            <tbody>           
                <tr>
                    <th>Nom</th>
                    <td>{{ agent.agentLastName }}</td>
                </tr>
                <tr>
                    <th>Prénom</th>
                    <td>{{ agent.agentFirstName }}</td>
                </tr>
                <tr>
                    <th>Date de naissance</th>
                    <td>{{ agent.agentBirthDate ? agent.agentBirthDate|date('Y-m-d') : '' }}</td>
                </tr>
                <tr>
                    <th>Code d'identification</th>
                    <td>{{ agent.agentIdentificationCode }}</td>
                </tr>
                <tr>
                    <th>Nationnalité</th>
                    <td>{{ agent.nationality }}</td>
                </tr>
                <tr>
                    <th>Spécialité</th>
                    <td>
                        {% for agents in agent.specialities %}
                            <li>{{agents.specialityName}}</li>
                        {% else %}
                        <li><em>vide</em></li>
                    {% endfor %}
                    </td>                
                </tr>   

            </tbody>
        </table>

        <a href="{{ path('agent_index') }}">Retour à la liste</a>
        
        {% if is_granted('ROLE_ADMIN') %}
                <a href="{{ path('agent_edit', {'id': agent.id}) }}">Modifier</a>    
                {{ include('agent/_delete_form.html.twig') }}           
        {% endif %}     

    </div>
 </div>
    
{% endblock %}