src/Entity/TypeMission.php
<?php

namespace App\Entity;

use App\Repository\TypeMissionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TypeMissionRepository::class)
 */
class TypeMission
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $typeMission_name;

    /**
     * @ORM\OneToMany(targetEntity=Mission::class, mappedBy="typeMission")
     */
    private $missions;

    public function __construct()
    {
        $this->missions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTypeMissionName(): ?string
    {
        return $this->typeMission_name;
    }

    public function setTypeMissionName(string $typeMission_name): self
    {
        $this->typeMission_name = $typeMission_name;

        return $this;
    }

    /**
     * @return Collection|Mission[]
     */
    public function getMissions(): Collection
    {
        return $this->missions;
    }

    public function addMission(Mission $mission): self
    {
        if (!$this->missions->contains($mission)) {
            $this->missions[] = $mission;
            $mission->setTypeMission($this);
        }

        return $this;
    }

    public function removeMission(Mission $mission): self
    {
        if ($this->missions->removeElement($mission)) {
            // set the owning side to null (unless already changed)
            if ($mission->getTypeMission() === $this) {
                $mission->setTypeMission(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->typeMission_name ;
    }




}

src/Form/TypeMissionType.php
<?php

namespace App\Form;

use App\Entity\TypeMission;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TypeMissionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('typeMission_name')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => TypeMission::class,
        ]);
    }
}

src/Controller/TypeMissionController.php
<?php

namespace App\Controller;

use App\Entity\TypeMission;
use App\Form\TypeMissionType;
use App\Repository\TypeMissionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class TypeMissionController extends AbstractController
{
    /**
     * @Route("/admin/type/mission/", name="type_mission_index", methods={"GET"})
     */
    public function index(TypeMissionRepository $typeMissionRepository): Response
    {
        return $this->render('type_mission/index.html.twig', [
            'type_missions' => $typeMissionRepository->findAll(),
        ]);
    }

    /**
     * @Route("/admin/type/mission/new", name="type_mission_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $typeMission = new TypeMission();
        $form = $this->createForm(TypeMissionType::class, $typeMission);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($typeMission);
            $entityManager->flush();

            return $this->redirectToRoute('type_mission_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('type_mission/new.html.twig', [
            'type_mission' => $typeMission,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/admin/type/mission/{id}", name="type_mission_show", methods={"GET"})
     */
    public function show(TypeMission $typeMission): Response
    {
        return $this->render('type_mission/show.html.twig', [
            'type_mission' => $typeMission,
        ]);
    }

    /**
     * @Route("/admin/type/mission/{id}/edit", name="type_mission_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, TypeMission $typeMission, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(TypeMissionType::class, $typeMission);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('type_mission_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('type_mission/edit.html.twig', [
            'type_mission' => $typeMission,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/admin/type/mission/{id}", name="type_mission_delete", methods={"POST"})
     */
    public function delete(Request $request, TypeMission $typeMission, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$typeMission->getId(), $request->request->get('_token'))) {
            $entityManager->remove($typeMission);
            $entityManager->flush();
        }

        return $this->redirectToRoute('type_mission_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/type_mission/_delete_form.html.twig
<form method="post" action="{{ path('type_mission_delete', {'id': type_mission.id}) }}" onsubmit="return confirm('Etes vous sur de vouloir supprimmer cet item ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ type_mission.id) }}">
    <button class="btn btn-danger space_4">Supprimer</button>
</form>

templates/type_mission/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success space_4">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/type_mission/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier un type de Mission{% endblock %}

{% block main %}
    
    {{ include('type_mission/_form.html.twig', {'button_label': 'Modifier'}) }}

    <a href="{{ path('type_mission_index') }}">Retour à la liste</a>

    {{ include('type_mission/_delete_form.html.twig') }}
{% endblock %}

templates/type_mission/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des types de Missions{% endblock %}

{% block main %}
    
    <table class="table">
        <thead>
            <tr>                
                <th>Nom</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for type_mission in type_missions %}
            <tr>                
                <td>{{ type_mission.typeMissionName }}</td>
                <td>
                    <a href="{{ path('type_mission_show', {'id': type_mission.id}) }}">Voir</a>
                    <a href="{{ path('type_mission_edit', {'id': type_mission.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
  
    {% if is_granted('ROLE_ADMIN') %}
              <a href="{{ path('type_mission_new') }}">Création nouveau Type de Mission</a>
    {% endif %}   

{% endblock %}

templates/type_mission/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Création nouveau type de Missions{% endblock %}

{% block main %}
   
    {{ include('type_mission/_form.html.twig') }}

    <a href="{{ path('type_mission_index') }}">Retour à la liste</a>
{% endblock %}

templates/type_mission/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Type de Mission{% endblock %}

{% block main %}
  
    <table class="table">
        <tbody>            
            <tr>
                <th>Nom</th>
                <td>{{ type_mission.typeMissionName }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('type_mission_index') }}">Retour à la liste</a>

    <a href="{{ path('type_mission_edit', {'id': type_mission.id}) }}">Modifier</a>

    {{ include('type_mission/_delete_form.html.twig') }}
{% endblock %}