src/Entity/Nationality.php
<?php

namespace App\Entity;
use App\Repository\NationalityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=NationalityRepository::class)
 */
class Nationality
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nationality_name;

    /**
     * @ORM\OneToMany(targetEntity=Target::class, mappedBy="nationality")
     */
    private $targets;

    /**
     * @ORM\OneToMany(targetEntity=Contact::class, mappedBy="nationality")
     */
    private $contacts;

    /**
     * @ORM\OneToMany(targetEntity=Agent::class, mappedBy="nationality")
     */
    private $agents;

    public function __construct()
    {
        $this->targets = new ArrayCollection();
        $this->contacts = new ArrayCollection();
        $this->agents = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNationalityName(): ?string
    {
        return $this->nationality_name;
    }

    public function setNationalityName(string $nationality_name): self
    {
        $this->nationality_name = $nationality_name;

        return $this;
    }

    /**
     * @return Collection|Target[]
     */
    public function getTargets(): Collection
    {
        return $this->targets;
    }

    public function addTarget(Target $target): self
    {
        if (!$this->targets->contains($target)) {
            $this->targets[] = $target;
            $target->setNationality($this);
        }

        return $this;
    }

    public function removeTarget(Target $target): self
    {
        if ($this->targets->removeElement($target)) {
            // set the owning side to null (unless already changed)
            if ($target->getNationality() === $this) {
                $target->setNationality(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Contact[]
     */
    public function getContacts(): Collection
    {
        return $this->contacts;
    }

    public function addContact(Contact $contact): self
    {
        if (!$this->contacts->contains($contact)) {
            $this->contacts[] = $contact;
            $contact->setNationality($this);
        }

        return $this;
    }

    public function removeContact(Contact $contact): self
    {
        if ($this->contacts->removeElement($contact)) {
            // set the owning side to null (unless already changed)
            if ($contact->getNationality() === $this) {
                $contact->setNationality(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Agent[]
     */
    public function getAgents(): Collection
    {
        return $this->agents;
    }

    public function addAgent(Agent $agent): self
    {
        if (!$this->agents->contains($agent)) {
            $this->agents[] = $agent;
            $agent->setNationality($this);
        }

        return $this;
    }

    public function removeAgent(Agent $agent): self
    {
        if ($this->agents->removeElement($agent)) {
            // set the owning side to null (unless already changed)
            if ($agent->getNationality() === $this) {
                $agent->setNationality(null);
            }
        }

        return $this;
    }
       
    public function __toString()
    {
        return $this->nationality_name ;
    }

}

src/Form/NationalityType.php
<?php

namespace App\Form;

use App\Entity\Nationality;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class NationalityType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nationality_name')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Nationality::class,
        ]);
    }
}

src/Controller/NationalityController.php
<?php

namespace App\Controller;

use App\Entity\Nationality;
use App\Form\NationalityType;
use App\Repository\NationalityRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class NationalityController extends AbstractController
{
    /**
     * @Route("/admin/nationality/", name="nationality_index", methods={"GET"})
     */
    public function index(NationalityRepository $nationalityRepository): Response
    {
        return $this->render('nationality/index.html.twig', [
            'nationalities' => $nationalityRepository->findAll(),
        ]);
    }

    /**
     * @Route("/admin/nationality/new", name="nationality_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $nationality = new Nationality();
        $form = $this->createForm(NationalityType::class, $nationality);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($nationality);
            $entityManager->flush();

            return $this->redirectToRoute('nationality_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('nationality/new.html.twig', [
            'nationality' => $nationality,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/admin/nationality/{id}", name="nationality_show", methods={"GET"})
     */
    public function show(Nationality $nationality): Response
    {
        return $this->render('nationality/show.html.twig', [
            'nationality' => $nationality,
        ]);
    }

    /**
     * @Route("/admin/nationality/{id}/edit", name="nationality_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Nationality $nationality, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(NationalityType::class, $nationality);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('nationality_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('nationality/edit.html.twig', [
            'nationality' => $nationality,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/admin/nationality/{id}", name="nationality_delete", methods={"POST"})
     */
    public function delete(Request $request, Nationality $nationality, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$nationality->getId(), $request->request->get('_token'))) {
            $entityManager->remove($nationality);
            $entityManager->flush();
        }

        return $this->redirectToRoute('nationality_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/nationality/_delete_form.html.twig
<form method="post" action="{{ path('nationality_delete', {'id': nationality.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ nationality.id) }}">
    <button class="btn btn-danger space_4">Supprimer</button>
</form>

templates/nationality/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier une Nationalité{% endblock %}

{% block main %}
    
    {{ include('nationality/_form.html.twig', {'button_label': 'Modifier'}) }}

    <a href="{{ path('nationality_index') }}">Retour à la liste</a>

    {{ include('nationality/_delete_form.html.twig') }}
{% endblock %}

templates/nationality/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des Nationalités{% endblock %}

{% block main %}
   
    <table class="table">
        <thead>
            <tr>                
                <th>Nationalité</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for nationality in nationalities %}
            <tr>                
                <td>{{ nationality.nationalityName }}</td>
                <td>
                    <a href="{{ path('nationality_show', {'id': nationality.id}) }}">Voir</a>
                    <a href="{{ path('nationality_edit', {'id': nationality.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">vide</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if is_granted('ROLE_ADMIN') %}
             <a href="{{ path('nationality_new') }}">Création nouvelle Nationalité</a>  
    {% endif %}    

{% endblock %}

templates/nationality/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Création nouvelle Nationalité{% endblock %}

{% block main %}
   
    {{ include('nationality/_form.html.twig') }}

    <a href="{{ path('nationality_index') }}">Retour à la liste</a>
{% endblock %}

templates/nationality/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nationalité{% endblock %}

{% block main %}

    <table class="table">
        <tbody>            
            <tr>
                <th>Nationalité</th>
                <td>{{ nationality.nationalityName }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('nationality_index') }}">Retour à la liste</a>

    <a href="{{ path('nationality_edit', {'id': nationality.id}) }}">Modifier</a>

    {{ include('nationality/_delete_form.html.twig') }}
{% endblock %}