src/Entity/TypeHideaway.php
<?php

namespace App\Entity;

use App\Repository\TypeHideawayRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TypeHideawayRepository::class)
 */
class TypeHideaway
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $typeHideaway_name;

    /**
     * @ORM\OneToMany(targetEntity=Hideaway::class, mappedBy="typeHideaway")
     */
    private $hideaways;

    public function __construct()
    {
        $this->hideaways = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTypeHideawayName(): ?string
    {
        return $this->typeHideaway_name;
    }

    public function setTypeHideawayName(string $typeHideaway_name): self
    {
        $this->typeHideaway_name = $typeHideaway_name;

        return $this;
    }

    /**
     * @return Collection|Hideaway[]
     */
    public function getHideaways(): Collection
    {
        return $this->hideaways;
    }

    public function addHideaway(Hideaway $hideaway): self
    {
        if (!$this->hideaways->contains($hideaway)) {
            $this->hideaways[] = $hideaway;
            $hideaway->setTypeHideaway($this);
        }

        return $this;
    }

    public function removeHideaway(Hideaway $hideaway): self
    {
        if ($this->hideaways->removeElement($hideaway)) {
            // set the owning side to null (unless already changed)
            if ($hideaway->getTypeHideaway() === $this) {
                $hideaway->setTypeHideaway(null);
            }
        }

        return $this;
    }

    
    public function __toString()
    {
        return $this->typeHideaway_name ;
    }    
    

}

src/Form/TypeHideawayType.php
<?php

namespace App\Form;

use App\Entity\TypeHideaway;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TypeHideawayType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('typeHideaway_name')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => TypeHideaway::class,
        ]);
    }
}

src/Controller/TypeHideawayController.php
<?php

namespace App\Controller;

use App\Entity\TypeHideaway;
use App\Form\TypeHideawayType;
use App\Repository\TypeHideawayRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class TypeHideawayController extends AbstractController
{
    /**
     * @Route("/admin/type/hideaway/", name="type_hideaway_index", methods={"GET"})
     */
    public function index(TypeHideawayRepository $typeHideawayRepository): Response
    {
        return $this->render('type_hideaway/index.html.twig', [
            'type_hideaways' => $typeHideawayRepository->findAll(),
        ]);
    }

    /**
     * @Route("/admin/type/hideaway/new", name="type_hideaway_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $typeHideaway = new TypeHideaway();
        $form = $this->createForm(TypeHideawayType::class, $typeHideaway);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($typeHideaway);
            $entityManager->flush();

            return $this->redirectToRoute('type_hideaway_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('type_hideaway/new.html.twig', [
            'type_hideaway' => $typeHideaway,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/admin/type/hideaway/{id}", name="type_hideaway_show", methods={"GET"})
     */
    public function show(TypeHideaway $typeHideaway): Response
    {
        return $this->render('type_hideaway/show.html.twig', [
            'type_hideaway' => $typeHideaway,
        ]);
    }

    /**
     * @Route("/admin/type/hideaway/{id}/edit", name="type_hideaway_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, TypeHideaway $typeHideaway, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(TypeHideawayType::class, $typeHideaway);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('type_hideaway_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('type_hideaway/edit.html.twig', [
            'type_hideaway' => $typeHideaway,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/admin/type/hideaway/{id}", name="type_hideaway_delete", methods={"POST"})
     */
    public function delete(Request $request, TypeHideaway $typeHideaway, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$typeHideaway->getId(), $request->request->get('_token'))) {
            $entityManager->remove($typeHideaway);
            $entityManager->flush();
        }

        return $this->redirectToRoute('type_hideaway_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/type_hideaway/_delete_form.html.twig
<form method="post" action="{{ path('type_hideaway_delete', {'id': type_hideaway.id}) }}" onsubmit="return confirm('Etes vous sur de vouloir supprimmer cet item ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ type_hideaway.id) }}">
    <button class="btn btn-danger space_4">Supprimer</button>
</form>

templates/type_hideaway/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success space_4">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/type_hideaway/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier un type de Planque{% endblock %}

{% block main %}
    
    {{ include('type_hideaway/_form.html.twig', {'button_label': 'Modifier'}) }}

    <a href="{{ path('type_hideaway_index') }}">Retour à la liste</a>

    {{ include('type_hideaway/_delete_form.html.twig') }}
{% endblock %}

templates/type_hideaway/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des types de Planques{% endblock %}

{% block main %}
   
    <table class="table">
        <thead>
            <tr>                
                <th>Nom</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for type_hideaway in type_hideaways %}
            <tr>                
                <td>{{ type_hideaway.typeHideawayName }}</td>
                <td>
                    <a href="{{ path('type_hideaway_show', {'id': type_hideaway.id}) }}">Voir</a>
                    <a href="{{ path('type_hideaway_edit', {'id': type_hideaway.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>    

    {% if is_granted('ROLE_ADMIN') %}
             <a href="{{ path('type_hideaway_new') }}">Création nouvelle Planque</a>
    {% endif %}   

{% endblock %}

templates/type_hideaway/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Création nouveau type de Planque{% endblock %}

{% block main %}

    {{ include('type_hideaway/_form.html.twig') }}

    <a href="{{ path('type_hideaway_index') }}">Retour à la liste</a>
{% endblock %}

templates/type_hideaway/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Type de Planque{% endblock %}

{% block main %}
    
    <table class="table">
        <tbody>           
            <tr>
                <th>Nom</th>
                <td>{{ type_hideaway.typeHideawayName }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('type_hideaway_index') }}">Retour à la liste</a>

    <a href="{{ path('type_hideaway_edit', {'id': type_hideaway.id}) }}">Modifier</a>

    {{ include('type_hideaway/_delete_form.html.twig') }}
{% endblock %}